### ISSUE TITLE
URL Shortener Effective Implementation

### ISSUE THREAD

**Issue by ricardocarva** [Tav0nes/ShortURL#4]
## Issue 
I was reviewing the topic and I learned that to create an application that shortens URLs, we will need some form of storage to keep track of the mappings between the short codes and the original long URLs. 

## Possible Approaches:

1. In-Memory Storage:
Use a dictionary (map) to store URL mappings.
Only suitable for small-scale applications or prototypes.
Note: Data will be lost when the application stops running.

2.  Database Storage:
Use a database like SQLite, MySQL, PostgreSQL, or MongoDB to store URL mappings.
This would ensure data persistence and scalability.

3. External API
Use an external URL shortening service API (e.g., Bitly, TinyURL, Rebrandly).
This abstracts away the storage and management of URLs.

I think we should go with 3. @Tav0nes.
Thoughts?

**Comment by Tav0nes** [comment]
Let's go with 3rd option. 
We can research one of the APIs and see which one suits us best for this project.
